services:
  # Web service
  - type: web
    name: costrak-api
    env: bun
    buildCommand: bun install && bun run build
    startCommand: bun start
    autoDeploy: true
    envVars:
      - key: BUN_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
